In [22]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
data=pd.read_csv('cancer.csv')

In [24]:
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [25]:
data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [26]:
data=data.drop(['Unnamed: 32', 'id'], axis = 1)
data.diagnosis = [1 if each == "M" else 0 for each in data.diagnosis]

In [28]:
data.diagnosis

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    int64
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    int64
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [11]:
c=0
for k in data.diagnosis:
    if k=='M':
        data.diagnosis[c]=1
    else:
        data.diagnosis[c]=0

    c=c+1

C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.diagnosis[c]=0
C:\Users\NP\AppData\Local\Temp\ipykernel_9556\1466263238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [36]:
y = data.diagnosis
x0 = data.drop(['diagnosis'], axis = 1)

In [34]:
#d=np.array([0,10,20,200,40,50,100])

In [37]:
x=(x0 - np.min(x0)) / (np.max(x0) - np.min(x0))

In [38]:
print(x)

     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0       0.004229      0.002440        0.028867   0.235308         0.000028
1       0.004835      0.004177        0.031241   0.311707         0.000020
2       0.004629      0.004995        0.030559   0.282793         0.000026
3       0.002685      0.004791        0.018237   0.090762         0.000033
4       0.004770      0.003371        0.031758   0.304890         0.000024
..           ...           ...             ...        ...              ...
564     0.005068      0.005263        0.033380   0.347673         0.000026
565     0.004732      0.006641        0.030842   0.296427         0.000023
566     0.003902      0.006601        0.025458   0.201716         0.000020
567     0.004843      0.006895        0.032934   0.297367         0.000028
568     0.001824      0.005769        0.011265   0.042548         0.000012

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0            0.000065        0.000071             0.000035       0.000057
1            0.000018        0.000020             0.000016       0.000043
2            0.000038        0.000046             0.000030       0.000049
3            0.000067        0.000057             0.000025       0.000061
4            0.000031        0.000047             0.000025       0.000043
..                ...             ...                  ...            ...
564          0.000027        0.000057             0.000033       0.000041
565          0.000024        0.000034             0.000023       0.000041
566          0.000024        0.000022             0.000012       0.000037
567          0.000065        0.000083             0.000036       0.000056
568          0.000010        0.000000             0.000000       0.000037

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                  0.000019  ...      0.005966       0.004074
1                  0.000013  ...      0.005874       0.005503
2                  0.000014  ...      0.005541       0.006001
3                  0.000023  ...      0.003505       0.006229
4                  0.000014  ...      0.005299       0.003919
..                      ...  ...           ...            ...
564                0.000013  ...      0.005983       0.006206
565                0.000013  ...      0.005569       0.008992
566                0.000013  ...      0.004462       0.008021
567                0.000016  ...      0.006051       0.009267
568                0.000014  ...      0.002223       0.007139

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           0.043394    0.474612          0.000038           0.000156
1           0.037330    0.459803          0.000029           0.000044
2           0.035849    0.401740          0.000034           0.000100
3           0.023242    0.133451          0.000049           0.000204
4           0.035778    0.370240          0.000032           0.000048
..               ...         ...               ...                ...
564         0.039046    0.476493          0.000033           0.000050
565         0.036436    0.406911          0.000027           0.000045
566         0.029784    0.264222          0.000027           0.000073
567         0.043394    0.428068          0.000039           0.000204
568         0.013907    0.063141          0.000021           0.000015

     concavity_worst  concave points_worst  symmetry_worst  \
0           0.000167              0.000062        0.000108
1           0.000057              0.000044        0.000065
2           0.000106              0.000057        0.000085
3           0.000161              0.000061        0.000156
4           0.000094              0.000038        0.000056
..               ...                   ...             ...
564         0.000097              0.000052        0.000048
565         0.000076              0.000038        0.000060
566         0.000080              0.000033        0.000052
567         0.000221              0.000062        0.000096
568         0.000000              0.000000        0.000067

     fractal_dimension_worst
0                   0.000028
1                   0.000021
2                   0.000021
3                   0.000041
4                   0.000018
..                       ...
564                 0.000017
565                 0.000016
566                 0.000018
567                 0.000029
568                 0.000017

[569 rows x 30 columns]

In [41]:
print("x train: ", x_train.shape)
print("x test: ", x_test.shape)
print("y train: ", y_train.shape)
print("y test: ", y_test.shape)

x train:  (483, 30)
x test:  (86, 30)
y train:  (483,)
y test:  (86,)

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.15, random_state = 42)

In [40]:
from sklearn import linear_model
robot = linear_model.LogisticRegression()

robot.max_iter=90000
robot.fit(x_train, y_train)

LogisticRegression(max_iter=90000)

In [42]:
t=robot.predict(x_test)

v= y_test ==t
v=v.reset_index()
v=v.diagnosis
n=0
for i in v:
    if i==False : n=n+1

print(100-(n * 100)/len(v))

89.53488372093022